name: Executar Automação de Dados Diária

on:
  schedule:
    # Horários convertidos para UTC (Horário de Brasília + 3 horas)
    
    # 06h00, 08h00 e 09h00 de Segunda a Sexta
    - cron: '0 9,11,12 * * 1-5'
    
    # 09h30 de Segunda a Sexta
    - cron: '30 12 * * 1-5'
    
    # 18h00 de Segunda a Sexta
    - cron: '0 21 * * 1-5'
    
    # 21h00 e 23h00 de Segunda a Sexta (No UTC vira 00h e 02h de Terça a Sábado)
    - cron: '0 0,2 * * 2-6'
  
  # Permite execução manual pelo painel do GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Dá permissão para o token do GitHub Actions fazer alterações no repositório (Push)
    permissions:
      contents: write

    steps:
    - name: Checkout do código
      uses: actions/checkout@v6

    - name: Configurar Fuso Horário Local
      run: sudo timedatectl set-timezone America/Sao_Paulo

    - name: Configurar Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Executa o script que vai atualizar ou criar os CSVs dentro de ./data
    - name: Executar script de processamento
      # O "|| true" força o terminal a entender que a execução terminou com sucesso mesmo se o Python falhar
      run: python run_all.py || true

    # Identifica mudanças na pasta data/ e faz o push se houver novos dados
    - name: Commitar e enviar novas alterações de dados
      run: |
        # Configura o Git com o usuário padrão do robô do GitHub
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Adiciona apenas as modificações da pasta data
        git add data/
        
        # O "|| echo" evita que o workflow falhe caso o script rode mas não mude nada nos arquivos
        git commit -m "Bot: Atualização automática de dados [skip ci]" || echo "Nenhuma alteração nos dados hoje."
        
        # Envia as alterações de volta para a branch main
        git push origin main